"""Add live_from and live_to columns to quizzes table

Revision ID: 1960b35d498c
Revises: 
Create Date: 2025-07-26 12:20:06.668683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1960b35d498c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('live_to', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('live_to')
        batch_op.drop_column('live_from')

    # ### end Alembic commands ###
